builder:
  track: dev

labels:
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: golang:1.15.7-alpine3.13
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:dev
    action: build
    inline: |
      FROM scratch

      LABEL maintainer="estafette.io" \
            description="The ${ESTAFETTE_GIT_NAME} component is an Estafette extension to send build status updates to Slack for builds handled by Estafette CI"

      COPY ca-certificates.crt /etc/ssl/certs/
      COPY ${ESTAFETTE_GIT_NAME} /

      ENV ESTAFETTE_LOG_FORMAT="console"

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    container: slack-build-status
    repositories:
    - extensions
    path: ./publish
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        container: slack-build-status
        repositories:
        - extensions

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        container: slack-build-status
        repositories:
        - extensions

  tests:
    parallelStages:
      test-success:
        image: extensions/slack-build-status:${ESTAFETTE_BUILD_VERSION}
        workspace: estafette
        channels:
        - '#test-status'
        status: succeeded

      test-failure:
        image: extensions/slack-build-status:${ESTAFETTE_BUILD_VERSION}
        workspace: estafette
        channels:
        - '#test-status'
        status: failed

      push-to-docker-hub:
        image: extensions/docker:dev
        action: push
        container: slack-build-status
        repositories:
        - extensions

  slack-notify:
    image: extensions/slack-build-status:stable
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  windows:
    builder:
      os: windows
    clone: true
    stages:
      build:
        image: estafette/golang:1.15.7-nanoserver-1809
        shell: cmd
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=%ESTAFETTE_GIT_NAME% -X main.version=%ESTAFETTE_BUILD_VERSION% -X main.revision=%ESTAFETTE_GIT_REVISION% -X main.branch=%ESTAFETTE_GIT_BRANCH% -X main.buildDate=%ESTAFETTE_BUILD_DATETIME%" -o ./publish/%ESTAFETTE_GIT_NAME%.exe

      bake:
        image: extensions/docker:nanoserver-1809
        action: build
        no-cache: true
        expand-variables: false
        container: slack-build-status
        repositories:
        - extensions
        dockerfile: Dockerfile.nanoserver-1809
        path: ./publish

      test-success:
        image: extensions/slack-build-status:${ESTAFETTE_BUILD_VERSION}
        workspace: estafette
        channels:
        - '#test-status'
        status: succeeded

      test-failure:
        image: extensions/slack-build-status:${ESTAFETTE_BUILD_VERSION}
        workspace: estafette
        channels:
        - '#test-status'
        status: failed

      push-to-docker-hub:
        image: extensions/docker:nanoserver-1809
        action: push
        container: slack-build-status
        repositories:
        - extensions
        tags:
        - nanoserver-1809
        pushVersionTag: false

  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      test-success:
        image: extensions/slack-build-status:${ESTAFETTE_BUILD_VERSION}
        workspace: estafette
        channels:
        - '#test-status'
        status: succeeded

      test-failure:
        image: extensions/slack-build-status:${ESTAFETTE_BUILD_VERSION}
        workspace: estafette
        channels:
        - '#test-status'
        status: failed

      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: slack-build-status
        repositories:
        - extensions
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: slack-build-status
        repositories:
        - extensions
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:stable
        workspace: estafette
        channels:
        - '#release-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:dev
        action: tag
        container: slack-build-status
        repositories:
        - extensions
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:stable
        workspace: estafette
        channels:
        - '#release-status'
        when:
          status == 'succeeded' ||
          status == 'failed'