FROM mcr.microsoft.com/windows/servercore:ltsc2019

COPY estafette-extension-slack-build-status.exe C:/estafette-extension-slack-build-status.exe

ENV ESTAFETTE_LOG_FORMAT="console"

USER ContainerAdministrator

ENTRYPOINT ["C:/estafette-extension-slack-build-status.exe"]